
# version: '3.9'
services:
  postgres:
    # image: postgres:bullseye
    image: ${IMAGE_NAME}:${VERSION}
    container_name: ${CONTAINER_NAME}
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${PG_DB_NAME}"
    ports:
      - "${ACCESS_PORT}:${TARGET_PORT}"
    networks:
      - ${NETWORK_NAME}  # This sets the actual network name in Docker
    volumes:
      - "${BACKUP}:${SOURCE_LOCATION}"
    env_file:
      - .env
    restart: always
networks:
#  default:
   pg_master_network:
    name: ${NETWORK_NAME}  # This sets the actual network name in Docker
    driver: bridge
    ipam: 
      config: 
        - subnet: "${SUBNET}"
