
# version: '3.9'
services:
  __SERVICE_NAME__: # We will replace the value from .env from dreload.sh file
    image: ${IMAGE_NAME}:${VERSION}
    container_name: ${CONTAINER_NAME}
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${PG_DB_NAME}"
      POSTGRES_MAX_CONNECTIONS: "${POSTGRES_MAX_CONNECTIONS}"
    ports:
      - "${ACCESS_PORT}:${TARGET_PORT}"
    # # networks: # Define the network configuration As per the original comment
    # networks:
    #   - default_network
    volumes:
      - "${BACKUP}:${SOURCE_LOCATION}"
    env_file:
      - .env
    restart: always
# # networks: # Define the network configuration As per the original comment
# networks:
#    default_network:   # Use a static internal name
#     name: ${NETWORK_NAME}  # This sets the actual network name in Docker
#     driver: bridge
#     ipam: 
#       config: 
#         - subnet: "${SUBNET}"
